### ISSUE TITLE
units in moment images

### ISSUE THREAD

**Issue by vdhulst** [SoFiA-Admin/SoFiA-2#1]
When comparing moment0 and moment1 images made with SoFiA-2 with those made with SoFiA-1.3.1 I noticed that the former have different units. SoFiA-2 appears to produce moment0 images in units of mJy/beam rather than mJy/beam.km/s and moment2 images in units of channel number rather than km/s. The mask cube appears to have the right velocity information. 

I also noticed that the products: mask, mom0, mom1, mom2 headers are very minimal and that a lot of the information from the original header is lost. A nice feature of SoFiA-1.3.1 is that it retains most of the original header and its history and adds the parameters used by SoFiA to the history. I think SoFiA-2 should do this as well.

**Comment by SoFiA-Admin** [comment]
Thank you very much for testing the new pipeline and for reporting your findings.

Indeed, the moment maps are currently in units of channels rather than velocity/frequency units, as there is no WCS support yet. This will change once WCS support will be implemented. The mask cube is correct as it simply copies the relevant WCS header keywords from the data cube.

The second point is an interesting one. The reason for why those headers are minimal is that masks and moment maps are created from scratch by the pipeline and for that reason don’t have any history that predates their creation. In principle, we could consider copying the entire header from the data cube to the masks and moments, but this may not necessarily be desirable. For example, the header might contain history information about calibration and processing steps applied to the data cube even though these steps were never applied to the mask cube itself. The same is true for observational parameters such as the telescope name or beam information which simply don’t apply to the mask.

So, the question is whether we actually want all of that information copied into the mask and moment maps or not? I would be interested to hear everyone’s opinion on this matter.

**Comment by vdhulst** [comment]
It is OK for the moment to not use WCS support. The user can in principle convert to the proper units him/herself.

Re the headers: I personally prefer to have the entire header of the input data cube saved in the output cubes/images as they retain a history of the processing up to the last point. Then actually adding the SoFiA input parameters makes sense as this is the last reduction step. I often use some of this information, ranging from object name to observing date, observing frequency and observatory (required to calculate corrected radial velocity from observing frequency). Indeed interesting to hear other peoples opinion.

**Comment by SoFiA-Admin** [comment]
Update: WCS support has now been added to moment maps and spectra. When WCS is enabled by the user, all spectra and moment maps will use the respective WCS information from the header to convert the raw data values into world coordinates. E.g., if the flux unit is “Jy/beam” and the spectral unit is “m/s”, then the spectral axis of the spectrum will be in m/s, the moment 0 map in Jy/beam*m/s and the moment 1 and 2 maps in m/s.

Copying of the full header information into derived data cubes and maps is still work in progress.

**Comment by SoFiA-Admin** [comment]
A separate issue has been opened (#10) to capture the copying of header information from the input data cube to the output products of SoFiA 2. This issue can therefore be closed now.
