### ISSUE TITLE
Remove 3D noise variations after each smoothing operation in S+C

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#2]
Experience with https://github.com/SoFiA-Admin/SoFiA is showing that normalising the cube to the local noise after each S+C smoothing operation reduces significantly the number of detected artefacts. This in turn improves the results of the reliability calculation. Overall, this results in more complete and reliable data products, and with better detection masks for the individual objects. It would be good to implement this feature in SoFiA-2, too.

**Comment by SoFiA-Admin** [comment]
Noise normalisation during S+C finding has been implemented in SoFiA 2 (see 12be83af412127bc448f83ef6bb8f22996645757). It can be enabled by setting the new `scaleNoise.scfind` parameter to `true`. The regular settings of the `scaleNoise` module will be used to control the noise scaling. Note that noise scaling will need to be enabled for this to take effect, and S+C noise scaling will be carried out **in addition** to initial noise scaling. Please test the new feature carefully and advise of any problems encountered. I will leave this issue open for now until the new feature has been found to work as expected and yields satisfactory results.

Note that the memory footprint of S+C scaling is only about 3.25 × cube size thanks to an overall reduction in SoFiA 2’s memory usage implemented in 7847040aaf37ae05ba4f43ecf893b167accbd4a9.

**Comment by paoloserra** [comment]
@SoFiA-Admin I'm testing the per-kernel noise scaling but get strange results.

My tests would benefit from being able to write to disk a binary mask right after S+C, skipping the Linker. Having a user parameter such as `linker.enable` would be very helpful. Could you please do that?

**Comment by SoFiA-Admin** [comment]
@paoloserra The new `linker.enable` option is now available (see 6b6da617193d0e5cdac307465c6d2ed5ff99354e). If set to `false`, the pipeline will merely write the binary mask after source finding and then terminate, so the new option is only really useful as a diagnostic tool for examining the binary mask.

**Comment by SoFiA-Admin** [comment]
@paoloserra Changed my mind again and instead implemented a special debugging mode, as I didn’t like the option of disabling the linker which requires a lot of sanity checking and increases the complexity of the code a lot. You can now simply set a new `pipeline.debug = true` option which will automatically write the binary mask after source finding into a file named `sofia_debug_binary_mask.fits`.

This is a much simpler and cleaner solution which still provides the information you requested. In addition, it can be used to produce all kinds of additional debugging output in the future, if needed.

**Comment by paoloserra** [comment]
@SoFiA-Admin I am more in favour of gaining back at least some of the flexibility of SoFiA-1. The ability of creating a binary mask was very useful. Also, the ability of skipping unnecessary steps was good. As it is, in SoFiA-2 one is forced to run the Linker even if they don't want to. The fact that the debug option will produce a binary mask is not intuitive. Making a binary mask is something generally useful, not a niche application.

I don't understand the objection about having too many sanity checks. Maybe I'm thinking Python, but it's quite simple to add a condition where all steps that require running the Linker are skipped (with an appropriate log message) if the Linker is not enabled.

**Comment by SoFiA-Admin** [comment]
The reason for why I am shying away from adding too much flexibility into SoFiA 2 is that it would result in a significant complexity burden that can be difficult to control. We’ve seen this problem in SoFiA 1, where there are now so many degrees of freedom, that changing just one minor aspect of the code suddenly exposes side effects in completely different parts of the code that we didn’t foresee. This is a mistake that we should not repeat with SoFiA 2.

For that reason I would rather prefer the debugging option, as it minimises complexity (requiring only a single additional line of code, namely writing the mask after source finding if debugging is enabled) while achieving the desired outcome. Writing the mask prior to linking clearly is a non-standard feature that the average user will not want to use, so the least complex implementation should therefore be favoured.

The linker, on the other hand, is one of the most central components of the pipeline, and it must be run in virtually every situation, as otherwise most of the other components would not function. For that reason cannot be disabled in SoFiA 2. For example, the linker is needed to ensure that we have valid sources in our mask, determine how many sources there are, ensure that they are numbered in consecutive order, measure their basic properties as needed by the reliability module, ensuring that all of these parameters are normalised by the noise level, etc. This means that skipping the linker would have an awful lot of implications down the line that are difficult to assess and keep track of, thereby adding a substantial degree of complexity to the code for very little benefit.

**Comment by paoloserra** [comment]
I disagree. I don't think that this would add any significant complexity. I think that SoFiA-1's flexibility was not at all a mistake. Most problems with SoFiA-1 come from its dependencies (which SoFiA-2 removes) not from its modularity and flexibility. The latter are great and allow for a much better understanding of what SoFiA actually does.

I think that we should discuss this at our telecons.

**Comment by SoFiA-Admin** [comment]
I am happy to discuss this topic at the next telecon. However, if my memory serves me right, then we already discussed this in the past and explicitly agreed on focussing the functionality of SoFiA 2 on the specific needs of extragalactic HI surveys with SKA precursors and pathfinders, with SoFiA 1 still being available to those who require more flexibility. This was to ensure that we have a fully functional and satisfactory tool at hand when the first data arrive.

A pre-linker mask is certainly not required for that purpose. Providing such a mask as a special debugging output would therefore appear perfectly appropriate given that this requires only a single line of code to be added rather than a more complex rewrite of parts of the pipeline to accommodate the far more momentous option of disabling of the linker (which we won’t be able to do in our survey data processing anyway).

**Comment by SoFiA-Admin** [comment]
@paoloserra Your second request of allowing negative sources to be retained after linking has also been implemented (see 143e982cdc0276a3d3cba66ca6b763c05ac21f09). A new user option named `linker.keepNegative` has been created to control this. The parametrisation module has been updated as well to be able to correctly handle sources with negative flux.

Note that the reliability module will need to be disabled for this to work. Also note that negative sources will not appear in the moment-1 and moment-2 maps for obvious reasons.

**Comment by paoloserra** [comment]
> we already discussed this in the past and explicitly agreed on focussing the functionality of SoFiA 2 on the specific needs of extragalactic HI surveys with SKA precursors and pathfinders

I  fully agree, and that's why interesting SoFiA-1 algorithms that have not been used a lot in the past years are not in SoFiA-2 (e.g., CNHI, 2D1D).

However, I don't think that we ever agreed to make SoFiA-2 less modular. Forcing one to always run the Linker reduces modularity while not removing any algorithms.

I often find myself in the situation of wanting to test different linker settings or reliability settings starting from a same binary mask. Creating the binary mask is by far the most time-consuming step, so it makes a lot of sense that one does not want to repeat that step every time they want to change the linker settings or the reliability settings.

My experience with many users (in fact, with most users I've been working with) is that creating and inspecting a binary mask, and  then seeing how the detection mask changes after the linker and the reliability steps, is very useful and instructive. These step-by-step approach helps users understanding what the different steps of source finding are, thus creating a community of users who understand what they are doing and how they can use SoFiA. I don't think that this is something that should be relegated to a debugging role.

**Comment by SoFiA-Admin** [comment]
Let’s continue this discussion on Monday at our weekly meeting, which is probably more efficient than exchanging arguments via GitHub.

The case you describe, by the way, would be pretty straightforward to implement as well by simply having an additional option of writing the binary mask prior to linking **in addition** to the regular mask after linking.

**Comment by paoloserra** [comment]
> an additional option of writing the binary mask prior to linking

That's be much better than a debugging option indeed, thanks.

**Comment by SoFiA-Admin** [comment]
@paoloserra The proposed change has now been implemented, and a new option, `output.writeRawMask`, is now available to write out the raw binary mask prior to linking (see da207c5ea481f30b5dbf78be47fa95fb53428304). This will not affect anything else, and the pipeline will continue to run thereafter. The `pipeline.debug` option is obsolete and has been removed again.

**Comment by paoloserra** [comment]
I'm finding significant results between SoFiA-1 and SoFiA-2. I think that this is related to a significant difference in the smoothing algorithms and not so much to a diffetence in the per-SCkernel noise scaling. So I've opened issue #4  on this, which is of course related to the present issue.

**Comment by paoloserra** [comment]
The feature requested in this issue has been added to SoFiA-2. Differences between SoFiA-1 and SoFiA-2 smoothing results are further discussed (although not fully understood) in #4 .
