### ISSUE TITLE
noise cube not generated when "scaleNoise.mode=spectral"

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#57]
The "output.writeNoise = true" only works when "scaleNoise.mode = local" not for "scaleNoise.mode = spectral".  Is this by design or a bug?

Options for users: Set appropriate parameters with "scaleNoise.mode = local" to generate the equivalent noise cube as if using "spectral".

Proposed changes:
* Have SoFiA output a noise spectrum rather than a cube in this case (a cube is not generated by SoFiA when normalizing noise on a per channel basis because it is not necessary from a coding/source finding perspective)
* Describe in the user manual how to force SoFiA to effectively generate a "spectral" noise cube using the "local" parameters.

**Comment by SoFiA-Admin** [comment]
Thank you for those suggestions. The creating of a noise spectrum in the case of spectral noise scaling has now been implemented (see 456a2d9dc1592cf9e0e2eda27b68cc47792191bb). This is controlled in the same way as with local noise scaling by setting `output.writeNoise = true`, but instead of writing a noise cube SoFiA will write a plain text file containing the measured noise value in each spectral channel. The file suffix will be `_noise.txt` (instead of `_noise.fits` for local noise scaling). The user manual and documentation has been updated to explain this new feature.

**Comment by SoFiA-Admin** [comment]
Out of curiosity, I just tested mimicking spectral noise scaling using the local noise scaling algorithm, and this actually seems to work as expected. If you set the spectral window and grid size to 1 and the spatial window and grid size to a very large value greater than the data cube size (e.g. 99999), then SoFiA will effectively measure and divide by the noise in each spectral channel. If `output.writeNoise` is set to `true`, then a FITS cube with the noise measurement in each channel will be generated, although such a cube is of little practical use, as the noise is constant for all pixels of a channel anyway. I might add a sentence to the user manual to point out this possibility, although using the spectral noise scaling algorithm will be significantly faster and more efficient in any case.

**Comment by SoFiA-Admin** [comment]
As discussed on Monday, this issue has been fixed and can now be closed.
