### ISSUE TITLE
Problem with spec table header

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#60]
The 3rd column name, "flux density", in the _spec.txt tables for each source, has a space which screws up the ability to read in the table with the correct header information in astroy.table or astropy.io.ascii.  Adding quotes around the column name fixes the problem.

I also noticed that the header of the *_spec.txt output differs in format from *_cat.txt in terms of the way the columns are described.  In principle, this isn't a problem of course, but it might be nice to be consistent.

*_cat.txt files have column headers like:
`# Header rows:`
`#   1 = column number`
`#   2 = parameter name`
`#   3 = parameter unit`
`#`
`#                           1             2             3 ...`
`#                        name            id             x ...`
`#                           -             -           pix ...`

versus *_spec.txt files don't have a column number (or description of the first three rows):
`#`
`#  Channel         Frequency      Flux density    Pixels`
`#        -                Hz           Jy/beam         -`

**Comment by SoFiA-Admin** [comment]
Thanks for that suggestion. I have updated the spectrum header (see 5e583e9471226df189510d23e6a178c0ef69bad8) to abbreviate the column names (`chan` instead of `Channel`, `f_sum` instead of `Flux density`, etc.) to make it consistent with the source catalogue and easier to parse in Python. I have also changed the format of the header to be more in line with that of the plain-text source catalogue. Let me know if you find any problems with the new spectrum format.

**Comment by kmhess** [comment]
I would make a further suggestion.  Now the spectral column is written as `freq` or `velo`, but the spectral column in the _cat.txt file is written as `freq`, `v_app`, `v_rad`, or `v_opt`.  I would suggest that these are kept consistent between the two, to maintain whatever information is encoded in the subscript.

**Comment by paoloserra** [comment]
Agreed.

Somewhat related, having now looked at the relevant code, I wonder why we don't just use the input cube's CTYPE3 as column name.

https://github.com/SoFiA-Admin/SoFiA-2/blob/5e583e9471226df189510d23e6a178c0ef69bad8/src/DataCube.c#L4854-L4888

**Comment by SoFiA-Admin** [comment]
Thanks for those suggestions. I agree that it would be useful to distinguish between `v_opt`, `v_rad` and `v_app` in the spectrum as well. This should be straightforward to change.

I am not sure if simply copying the value of `CTYPE3` is useful, as these values are not particularly instructive and can have a large number of different formats. Translating something as incomprehensible as `FELO` to `v_opt` is far more user-friendly in my opinion. In addition, such a change would break SoFiA-X, which relies on certain consistent parameter names to be present in the catalogue rather than the array of different velocity and frequency definitions allowed by the FITS standard.

**Comment by SoFiA-Admin** [comment]
I updated the header of the spectrum to replace `velo` with `v_opt`, `v_rad` or `v_app` as appropriate (4c6282650c5624cd166ba550a64cf56ef5d242e1).

**Comment by SoFiA-Admin** [comment]
As this issue has been dealt with, it can now be closed.
