### ISSUE TITLE
Bug in how *_spec.txt units are sometimes written.

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#69]
I found a bug in the way the *_spec.txt headers are sometimes written: the units for the spectral column aren't in the right place (see screenshot).  I discovered this while testing the image pipeline code on the HCG 44 cube.  At first I thought it was a problem with the 'v_app' because I didn't see it on cubes with 'freq' or 'v_opt', however the problem doesn't occur with the sofia test cube which is also 'v_app', so now I think it has to do with the units itself in the HCG44 cube, which are written out as 'M/S' instead of 'm/s'.

<img width="425" alt="Screen Shot 2022-04-09 at 16 14 43" src="https://user-images.githubusercontent.com/14857798/162578028-e0831f55-8862-4734-8822-2dddcdcdd729.png">

**Comment by SoFiA-Admin** [comment]
Thanks for reporting this issue. Looking through the code, I suspect that the problem is caused by a peculiarity in your FITS file. While I don’t have access to the original header, my suspicion is that the `CUNIT3` string is `M/S` followed by a large number of trailing spaces. Those trailing spaces would then be copied across into the spectrum, resulting in the unit string filling the entire available column width.

I believe I have fixed this problem now by trimming all leading and trailing whitespace from the unit string in the FITS header before writing it to the spectrum (see 1ea552bf66fc8c298fbf25e3e51d5ef51165a464). This should resolve the issue of trailing spaces messing up the alignment. Please test and let me know if the problem still occurs.

**Comment by kmhess** [comment]
Looks good to me!  That fixed the problem.
