### ISSUE TITLE
add skellam plots

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#7]
Relvant for validating the auto-scaling of the reliability kernel proposed in #6

**Comment by SoFiA-Admin** [comment]
**Update:** A first attempt of implementing the same Skellam plot feature as in SoFiA 1 can be found at
https://github.com/SoFiA-Admin/SoFiA-2/blob/a2e086869b4904993b2e64d4233930d9e2d409ca/src/LinkerPar.c#L1071
but is currently commented out, as there is still ongoing discussion on the correct normalisation of the kernel density estimator.

**Comment by paoloserra** [comment]
Thanks @SoFiA-Admin .

I think the implementation is good.

Here's two examples: one with a reliability kernel which is clearly too small (the red line is offset towards negative values compared to the black reference Gaussian curve); the other with a 2x larger kernel, which is much better.

Note that in both cases the slope is close to that of the reference Gaussian curve, which indicates that the normalisation is ok.

I think this already very is useful as is, and should be included in master. It provides a much needed guidance for choosing a reasonable reliability kernel.

![sky_ldev_v2_38sigma_03_skellam](https://user-images.githubusercontent.com/6591265/114834262-af048700-9dd0-11eb-8d33-0b5a69381c85.png)
![sky_ldev_v2_38sigma_04_skellam](https://user-images.githubusercontent.com/6591265/114834281-b2980e00-9dd0-11eb-91c7-f4e8a2e6b21d.png)

**Comment by SoFiA-Admin** [comment]
Thanks, @paoloserra, for testing. I have now finalised and activated Skellam plots in SoFiA 2 (see 64e360010c056881fd68f6b30b9250d63a3c1c96). The original implementation still had some issues with normalisation of the Skellam parameter which are now fixed.

For the calculation of positive and negative densities I am now setting the amplitude of the Gaussian kernel to 1 rather than the integral which was used in the original reliability calculation in SoFiA 2. While this does not affect the reliability values themselves, it would appear to produce Skellam distributions that are more in line with those of SoFiA 1, suggesting that a similar normalisation could be used there.

In addition, I am now renormalising the Skellam distribution to a standard deviation of 1 when creating the plot, as this will make it easier to compare with the standard Gaussian distribution. This is something we had discussed a while ago and which appears to be working very well.

Please test the final implementation and let me know if you find any issues. The new Skellam plots will now be generated whenever `reliability.plot = true`, and the file suffix will be `_skellam.eps`.

**Comment by paoloserra** [comment]
I'd like to suggest two changes:

- X axis label `(P-N)/sqrt(P+N)  -- normalised to width = 1` instead of the little informative `Skellam parameter`
- X axis range fixed to -4,4 or, alternatively, to fixed percentiles of the distribution, but not to min,max. I got a Skellam plot ranging from -15 to 15 and that's not useful to judge whether the median is close to 0.

**Comment by SoFiA-Admin** [comment]
Done. An example of the final plot based on the WSRT test cube is attached. The Skellam distribution now nicely follows the standard Gaussian as a result of scaling to σ = 1. I will close this issue as resolved now. Feel free to reopen if you find any outstanding problems.
![skyN_skellam](https://user-images.githubusercontent.com/6572706/115666907-bea74100-a377-11eb-9b95-a1979b71c7fc.png)
