### ISSUE TITLE
Can we create a PVD of the mask too?

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#73]
We create and use the PVD of the mask within https://github.com/kmhess/SoFiA-image-pipeline to plot the mask outline on top of the data PVD. This is generally useful as a diagnostic and analysis tool.

It would be great if the FITS PVD of the mask were created by SoFiA itself.

**Comment by SoFiA-Admin** [comment]
This has now been implemented using a slightly simplified version of the implementation created by @vdhulst. As the number of PV diagrams has now increased to 4 (one third of all cubelet outputs are now PV diagrams), I have also set up a new user parameter, `output.writePV`, that can be used to explicitly enable or disable the generation of PV diagrams. It is set to `false` by default, meaning that PV diagrams must be explicitly enabled by the user. This will keep the number of default output products more manageable, as otherwise new users may get overwhelmed by the large number of different output files created for each detection.
