### ISSUE TITLE
Produce PV diagram along the kinematical minor axis

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#84]
This PVD would be along the axis perpendicular to the kinematical major axis, whose PA is included in the SoFiA output catalogue.

It would provide additional diagnostics on
- the HI kinematics of bright and well resolved objects
- faint emission especially for faint and poorly resolved objects.

**Comment by vdhulst** [comment]
This will indeed a very useful addition and serves different purposes. 

In the case of resolved galaxies it is an immediate indication of whether the chosen PA and centre are adequate as errors immediately translate into peculiar shapes and asymmetries in the major axis and minor axis PV diagrams. 
Moreover, if the centre and PA have been determined appropriately both give diagnostics of different kinds as due to the projection the major axis is most sensitive to circular/non-circular motions and the minor axis to radial (in the plane of the galaxy) motions, i.e. inflows and outflows.

In the case of marginally resolved objects this is less clear, though having both will give a good indication of whether the choice of PA is appropriate. Two cross sections moreover give a factor two more sampling of the data cube to catch faint signal around the central position.

We could consider experimenting with adding minor axis PV diagram and looking at a number of different cases to assess its use for diagnostic purposes.

**Comment by paoloserra** [comment]
#90
