### ISSUE TITLE
Write catalogues of all pos and neg sources for visual inspection

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#9]
It would be useful to write to disc two output catalogues containing all positive and negative sources, respectively, right after reliability calculation. The catalogues would be meant for interactive visual inspection of the distribution of sources in the parameter space used for calculating reliability. Therefore, they could be limited to source ID, X, Y, Z, Rel + all parameters used for the reliability calculation. It would be good to write these catalogues to disc already in log10(absolute_value). This would allow easy plotting in, e.g., Topcat, as in the attached figure.

<img width="1440" alt="Screen Shot 2020-05-03 at 23 31 04" src="https://user-images.githubusercontent.com/6591265/80951676-99cd5d00-8df8-11ea-9d0e-b12d6c0dfe5d.png">

**Comment by paoloserra** [comment]
I've noticed that the current output catalogue does not allow a meaningful inspection of the results of the reliability calculation. This is because the parameter values in the catalogue do not allow users to accurately reconstruct the position of the detected sources in the reliability plots.

This may be happening because `rms` in the catalogue is not calculated in the same way as is done when normalising the cube to the local noise before running S+C.

The example below shows the "official" reliability plot from SoFiA-2 (top) and a plot where I overlay the source position reconstructed from the source catalogue on top of the "official" reliability plot (bottom). The sources are clearly the same (see top-right region) but there are clear differences, too.

In order to enable this higher level of scrutiny of the SoFiA-2 results I suggest that we raise the priority level of the present GitHub issue.

![sofia_rel](https://user-images.githubusercontent.com/6591265/106453710-0198fd00-648a-11eb-92dc-eee5482e1c6f.png)
![sofia_topcat](https://user-images.githubusercontent.com/6591265/106453721-052c8400-648a-11eb-90c1-a7720a297415.png)

**Comment by SoFiA-Admin** [comment]
This has now been implemented (see 068fb1e40e19fc22adf23ffb3e036e7bcb50d177). A new option, `reliability.debug` is now available. If set to `true`, then two catalogues containing the relevant reliability parameters of the negative and positive detections will be written to disc. The catalogues are currently hard-coded to be in VOTable format (XML), as this is most convenient for use in VO tools such as TOPCAT. Note that the (x, y, z) positions are geometric centroids rather than flux-weighted centroids, as the latter are not calculated by the linker in the interest of speed and memory usage.

I tested the new feature on the SoFiA test data cube, and everything would appear to work as expected, with the parameter plots looking identical to the reliability plots created natively by SoFiA. Let me know if you find any issues with the implementation or if you require any additional parameters.

**Comment by paoloserra** [comment]
Thank you @SoFiA-Admin . I've tested this. I  agree that the source parameters written to the new debugging catalogues are fine. The reliability plots can  be reproduced.

However, I have no way of matching sources in those catalogues to sources in the final (reliability-filtered) mask and catalogue. There are two problems.

- Source IDs do not match (I understand why; that's why we had an `old_ID` column  in SoFiA-1).
- The values of the X,Y,Z coordinates in the new catalogues do not seem to make sense. The cube is 789 x 730 pixels and 2250 channels. The final list of detections includes sources scattered across the full cube. The new debugging catalogues have sources only in the following intervals: X = [1, 23], Y = [1, 30], Z = [4, 204].

It would be good if you could confirm and fix at least the X,Y,Z issue. I understand the ID issue is trickier.

**Comment by SoFiA-Admin** [comment]
Sorry, that was just a bug in the code (using minus instead of plus) that is now fixed. I checked the positions for the SoFiA test cube, and they appear to be in the correct range now.
