### ISSUE TITLE
Continuum subtraction output and variable order

### ISSUE THREAD

**Issue by spectram** [SoFiA-Admin/SoFiA-2#91]
I perform image plane continuum subtraction by first clipping the signal at $2\sigma$ and then fitting a 0th-order polynomial. I notice that this is similar to SoFiA2 implementation before source finding. Would it be possible to save the continuum file and also give users the option to perform parameterization (& cubelet creation) on the continuum subtracted file? 

On a similar note, can the order (0 and 1) of the continuum per pixel be fitted as a free parameter? This would account for variations in the slope of the residual continuum from pixel to pixel. Since the spectrum is subtracted before fitting, the line probably is unlikely to affect the 'order'. If an 'order map' can be output as well, the residual continuum behaviour can be spatially quantified.

**Comment by SoFiA-Admin** [comment]
Thank you for those suggestions. In principle, most of what you are describing is already possible with the current version of SoFiA. Parameterisation of the continuum-subtracted file can be achieved by running SoFiA twice: the first time you would enable continuum subtraction (`contsub.enable = true`), disable source finding (`scfind.enable = false`) and then write the filtered data cube as the sole output product (`output.writeFiltered = true`). This first run simply uses SoFiA as a filter rather than a source finder to carry out continuum subtraction. Then you can run SoFiA again in regular source finding mode, but this time on the filtered (and hence continuum-subtracted) cube produced by the previous run.

With the continuum-subtracted cube at hand, it is also straightforward to obtain a continuum model cube by simply subtracting the filtered cube from the original data cube, e.g. using a simple Python script:

```python
from astropy.io import fits
hdu_orig = fits.open("datacube.fits")
hdu_filt = fits.open("datacube_filtered.fits")

hdu_orig[0].data -= hdu_filt[0].data
hdu_orig.writeto("datacube_cont.fits")

hdu_orig.close()
hdu_filt.close()
```

This will then give you a data cube containing just the fitted continuum model.

The only thing that is not currently possible is to have SoFiA automatically determine the optimal polynomial order to be fitted. Given that SoFiA is primarily a source finding pipeline rather than a sophisticated continuum subtraction tool, I am not sure if there was much benefit in implementing such a feature, in particular as SoFiA currently only supports 0th and 1st order fitting anyway. There are presumably far more sophisticated polynomial fitting algorithms out there which could be used to remove the continuum before feeding the cube into SoFiA for source finding.

**Comment by spectram** [comment]
Thank you for this tip. I will explore writing the filtered cube. In my workflow, I use SoFiA2 for parameterization as well (at least partially). I see it as a good way to consolidate post-imaging cube processing. CASA image analysis tool already has some excellent functionality, but the automation that the pipeline approach of SoFiA2 provides can be employed to augment cube processing and even standardise it to some level. That said, I see how source finding would be a higher priority for development at the moment. Accurate continuum subtraction might not contribute much in this regard, especially if the data is properly processed prior to running SoFiA2. Shall I close this issue for now?

**Comment by SoFiA-Admin** [comment]
Thank you for the detailed description of how you use SoFiA in your workflow. Indeed, continuum subtraction is not a high priority at the moment, but certainly an area that could benefit from some improvements to the currently implemented algorithm which is somewhat basic and was originally created to deal with continuum residuals in ASKAP data that had not been properly subtracted by the ASKAP data reduction pipeline.

Being an open-source project, everyone can of course make contributions to the SoFiA code, so if you have developed a more sophisticated continuum subtraction algorithm yourself, or know some else who has, then we would be delighted to look into replacing the current algorithm with the improved one. Likewise, if you are keen to help developing and improving certain parts of SoFiA, please don’t hesitate to get in touch.

Feel free to close the issue if you think that all of the points you raised have been addressed or clarified.

**Comment by spectram** [comment]
Sure. I do need to brush up on my C skills. Closing the issue for now.
