### ISSUE TITLE
Is it possible to output reliability plots as something other than eps?

### ISSUE THREAD

**Issue by healytwin1** [SoFiA-Admin/SoFiA-2#96]
Is it possible to output the reliability plots as something other than eps (such as png or pdf)? The latest MacOS no longer supports the viewing of eps files in Preview which has made opening and inspecting these plots rather challenging.

**Comment by vdhulst** [comment]
eps and ps are widely used formats which have the advantage they are not binary and are vector files. Not clear why Apple discontinues its support for this, but the easiest workaround for now is to install Ghostscript which has many format conversions including ps2pdf to go from (e)ps to pdf.

**Comment by SoFiA-Admin** [comment]
It is a shame that Apple has decided to no longer support the open PostScript format in their native document previewer. However, there is a plethora of other software that you could use instead. In addition to runnning `ps2pdf` as suggested by @vdhulst, any standard graphics software or document viewer that I have ever used on Linux natively supports the PostScript format, e.g. Okular, gv, GIMP, LibreOffice, xfig, Inkscape, to name just a few. I personally have been using gv for many years to view PostScript files and can recommend it due to its simplicity, ease-of-use and small memory footprint.

PostScript has several advantages, including being an open, standardised, widely-supported (with the recent exception of native Apple products, it seems) and vectorised format that is at the same time human-readable and for that reason straightforward to programmatically generate without requiring the installation of additional libraries (as would be needed for PDF export). Hence, we currently don’t have any plans to replace it with a different format.
