### ISSUE TITLE
cannot install SoFiA on M1 Mac

### ISSUE THREAD

**Issue by kanamoroo** [SoFiA-Admin/SoFiA-2#99]
I failed to install SoFiA on my M1 Mac (OS: 12.6.3).
If you have any workaround, please let me know.
Thank you very much in advance!

The error messages I got are as follows:
============================
_______________________________________________________________________

 Installing SoFiA
_______________________________________________________________________

  Compiling src/common.c
  Compiling src/statistics_flt.c
  Compiling src/statistics_dbl.c
  Compiling src/Table.c
  Compiling src/String.c
  Compiling src/Stack.c
  Compiling src/Path.c
  Compiling src/Array_dbl.c
  Compiling src/Array_siz.c
  Compiling src/Map.c
  Compiling src/Matrix.c
  Compiling src/LinkerPar.c
  Compiling src/Parameter.c
  Compiling src/Source.c
  Compiling src/Catalog.c
  Compiling src/Flagger.c
  Compiling src/WCS.c
  Compiling src/Header.c
  Compiling src/DataCube.c
  Compiling sofia.c
ld: warning: ignoring file /usr/local/lib/libwcs.dylib, building for
macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_wcs_errmsg", referenced from:
      _WCS_new in WCS.o
      _WCS_convertToWorld in WCS.o
      _WCS_convertToPixel in WCS.o
  "_wcsfix", referenced from:
      _WCS_new in WCS.o
  "_wcsfree", referenced from:
      _WCS_delete in WCS.o
  "_wcsini", referenced from:
      _WCS_new in WCS.o
  "_wcsp2s", referenced from:
      _WCS_convertToWorld in WCS.o
  "_wcspih", referenced from:
      _WCS_new in WCS.o
  "_wcss2p", referenced from:
      _WCS_convertToPixel in WCS.o
  "_wcsset", referenced from:
      _WCS_new in WCS.o
  "_wcsvfree", referenced from:
      _WCS_delete in WCS.o
ld: symbol(s) not found for architecture arm64
clang: fatal error: linker command failed with exit code 1 (use -v to
see invocation)
_______________________________________________________________________

 Installation complete
_______________________________________________________________________

  Please check above for any error messages  produced by the compiler
  before proceeding with the instructions below. If no error messages
  have occurred, you can choose to create a symbolic link in /usr/bin
  to make SoFiA available across your system:

    sudo ln -s /Users/kmatsui/software/SoFiA/SoFiA-2-master/sofia /usr/bin/sofia

  Alternatively, if you don't have root privileges on your system, an
  alias can be set in your .bashrc or .cshrc configuration file. Once
  complete, SoFiA can then be invoked via 'sofia <parameter_file>'.
============================

**Comment by SoFiA-Admin** [comment]
Thank you for reporting the SoFiA installation issue. Looking at the error messages, the problem seems to be occurring when linking against the WCSLIB library. By the look of it, your WCSLIB installation is compiled for a different architecture (macOS-x86_64) than the actual architecture of your computer (macOS-arm64). Hence, the compiler cannot link the WCSLIB library due to the mismatch, as it cannot find a version compiled for the correct architecture.

As I am not familiar with Mac, I don’t quite understand how such a mismatch could have occurred in the first place. A potential solution might be to reinstall or recompile WCSLIB, this time for the correct architecture. Alternatively, if you have a matching WCSLIB somewhere installation already, you could point the linker to it by specifying the absolute path to the shared object file, although this would require editing the compilation script where WCSLIB is currently linked with the `-lwcs` flag in line 85 by default.

**Comment by kanamoroo** [comment]
Thank you very much for your reply!
I changed the architecture from the macOS-arm64 to the macOS-x86_64 (by turning on the "open using Rosetta" in the "Terminal Info") and finally succeeded in installing the SoFiA!

https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9
